### PR TITLE
fix(hydro_lang): sim scheduler no longer terminates on quiescence

### LINKED ISSUE #2816: bug: Sim scheduler terminates on quiescence, preventing further interaction after `assert_yields_only`
I hit this trying to extend [this sample](https://hydro.run/docs/hydro/learn/quickstart/partitioned-counter#testing-the-partitioned-counter) from the quickstart. It felt pretty natural to duplicate more sends & assert_yields after, which was why it was confusing to then get the send error. 

## Bug

When using `assert_yields_only` / `assert_yields_only_unordered` in a sim test,
any subsequent `send()` call panics with `SendError` because the sim scheduler
has already terminated and dropped all DFIR state and input receivers.

## Minimal Repro

```rust
use hydro_lang::prelude::*;

pub struct Server;

#[test]
fn test_send_after_assert_yields_only() {
    let mut flow = FlowBuilder::new();
    let process = flow.process::<Server>();

    let (send_port, input) = process.sim_input();
    let output = input.atomic().end_atomic();
    let out_port = output.sim_output();

    flow.sim().exhaustive(async || {
        send_port.send(1u32);
        out_port.assert_yields_only([1u32]).await;

        // This panics with SendError — the scheduler has already terminated
        send_port.send(2u32);
        out_port.assert_yields_only([2u32]).await;
    });
}
```

Error:
```
thread panicked at hydro_lang/src/sim/compiled.rs:789:40:
called `Result::unwrap()` on an `Err` value: SendError { .. }
```

## Root Cause

`assert_yields_only` calls `assert_no_more()`, which awaits `stream.next()`
expecting `None`. The only way `None` is returned is when the output sender is
dropped — which happens when the scheduler task terminates.

The scheduler (`LaunchedSim::scheduler` in `hydro_lang/src/sim/compiled.rs`)
terminates via `break` when it reaches quiescence (no ready ticks, no ready
observations). This drops all DFIRs, their state, and their input receivers.

The sequence of events:
1. `assert_no_more()` awaits `stream.next()` → pends (sender still alive)
2. Scheduler reaches quiescence → `break`s out of loop → task completes
3. DFIRs dropped → output senders dropped → `stream.next()` returns `None`
4. `assert_no_more` succeeds
5. Test calls `send_port.send(...)` → input receiver already dropped → `SendError` panic

### PR DESCRIPTION
**Pull request by Benjscho**
Resolves #2816

The scheduler previously broke out of its loop on quiescence, dropping all DFIRs and input receivers. This caused subsequent send() calls to panic with SendError after assert_yields_only.

Fix: signal quiescence via Notify and pend, resuming when new input arrives. Receivers detect quiescence via a shared flag + Notify and yield None instead of blocking forever. Senders reset the flag and notify the scheduler.

Adds regression test: sim_send_after_assert_yields_only.

### CODE REVIEW

**Comment by Benjscho** [comment]
I also have another version that wraps the senders to ensure that the quiescence handling is always done, e.g.,
```
struct SimInputSender {
    inner: UnboundedSender<Bytes>,
    quiescent: Rc<Cell<bool>>,
    resume_notify: Rc<Notify>,
}

...

/// A receiver stream that yields `None` on quiescence instead of blocking forever.
struct SimOutputStream {
    inner: Rc<Mutex<UnboundedReceiverStream<Bytes>>>,
    quiescent: Rc<Cell<bool>>,
    quiescence_notify: Rc<Notify>,
}
```
but that felt like a little much to swap out the types. Maybe nice to do though as it means no duplication of the quiescence_aware future, and a little more misuse resistant

File: hydro_lang/src/sim/compiled.rs [hunk 1]
```diff
@@ -872,19 +941,26 @@ impl<T: Serialize + DeserializeOwned, O: Ordering, R: Retries> SimClusterSender<
...
         });
 
-        thunk(&move |member_id: u32, t: T| {
+        let result = thunk(&move |member_id: u32, t: T| {
             let payload = bincode::serialize(&t).unwrap();
             senders[member_id as usize].send(Bytes::from(payload))
-        })
+        });
+        quiescent.set(false);
+        resume_notify.notify_waiters();
```
Comment (shadaj) [inline hydro_lang/src/sim/compiled.rs]: Should this happen inside the closure? Otherwise in theory this could wake up the scheduler too early.

File: hydro_lang/src/sim/compiled.rs [hunk 2]
```diff
@@ -757,16 +798,23 @@ impl<T: Serialize + DeserializeOwned, O: Ordering, R: Retries> SimSender<T, O, R
...
+                    .clone(),
+                connections.quiescent.clone(),
+                connections.resume_notify.clone(),
+            )
         });
 
-        thunk(&move |t| sender.send(bincode::serialize(&t).unwrap().into()))
+        let result = thunk(&move |t| sender.send(bincode::serialize(&t).unwrap().into()));
+        quiescent.set(false);
+        resume_notify.notify_waiters();
```
Comment (shadaj) [inline hydro_lang/src/sim/compiled.rs]: Same question as below

**Review by shadaj — COMMENTED** [review]
Awesome! Have one question about when we signal new input, otherwise seems good!

File: hydro_lang/src/sim/compiled.rs (hunk 1 above)
Comment (Benjscho) [reply hydro_lang/src/sim/compiled.rs]: Good catch, fixed!

**Review by shadaj — APPROVED** [review]

**Comment by shadaj** [comment]
Tagged @MingweiSamuel in case there are thoughts on how to structure the `Cell` + `Notify`, maybe there are better constructs we should use.

File: hydro_lang/src/sim/compiled.rs [hunk 3]
```diff
@@ -819,20 +869,41 @@ impl<T: Serialize + DeserializeOwned, O: Ordering, R: Retries> SimClusterReceive
...
+            if quiescent.get() {
+                return Poll::Ready(None);
+            }
+            match notified_fut.as_mut().poll(cx) {
+                Poll::Ready(()) => {
+                    notified_fut.set(quiescence_notify.notified());
+                    Poll::Ready(None)
+                }
+                Poll::Pending => Poll::Pending,
+            }
```
Comment (MingweiSamuel) [inline hydro_lang/src/sim/compiled.rs]: Can simplify with the `ready!` macro (like `?` but for `Poll::Pending`)
```suggestion
            let () = ready!(notified_fut.as_mut().poll(cx));
            notified_fut.set(quiescence_notify.notified());
            Poll::Ready(None)
```
(untested)

File: hydro_lang/src/sim/compiled.rs [hunk 4]
```diff
@@ -513,22 +536,40 @@ impl<T: Serialize + DeserializeOwned, O: Ordering, R: Retries> SimReceiver<T, O,
...
```
Comment (MingweiSamuel) [inline hydro_lang/src/sim/compiled.rs]: could also use `ready!` here

**Review by MingweiSamuel — APPROVED** [review]
Maybe worth pulling these three fields into a single struct, to unify the abstraction, and also reduce the number of Rc's to 1/3?

File: hydro_lang/src/sim/compiled.rs (hunk 3 above)
Comment (Benjscho) [reply hydro_lang/src/sim/compiled.rs]: Nice, TIL

**Comment by Benjscho** [comment]
> Maybe worth pulling these three fields into a single struct, to unify the abstraction, and also reduce the number of Rc's to 1/3?

Yeah that sounds nicer! I'll take a pass there
