### PR TITLE
fix(hydro_lang): improve quality of sim assertion backtraces

### LINKED ISSUE #2305: Improve backtrace quality for simulation assertions
Right now, panics in simulation assertions show the original panic location, which is inside a helper function. It would be better to show the location of the original caller, but this requires using `#[track_caller]` which is not yet supported for async functions. We should explore a proper solution.

### PR DESCRIPTION
**Pull request by shadaj**
Fixes #2305

### CODE REVIEW

File: hydro_lang/src/sim/compiled.rs [hunk 1]
```diff
@@ -514,29 +523,104 @@ impl<T: Serialize + DeserializeOwned> SimReceiver<T, TotalOrder, ExactlyOnce> {
...
+        ChainedFuture {
+            first: self.assert_yields(expected),
+            second: self.assert_no_more(),
+            first_done: false,
+        }
+    }
+}
+
+pin_project_lite::pin_project! {
+    // A future that tracks the location of the `.await` call for better panic messages.
```
Comment (MingweiSamuel) [inline hydro_lang/src/sim/compiled.rs:577]:
```suggestion
    // A future that tracks the location of the `.await` call for better panic messages.
    //
    // `#[track_caller]` is important for us to create assertion methods because it makes
    // the panic backtrace show up at that method (instead of inside the call tree within
    // that method). This is e.g. what `Option::unwrap` uses. Unfortunately, `#[track_caller]`
    // does not work correctly for async methods (or `dyn Future` either), so we have to
    // create these concrete future types that (1) have `#[track_caller]` on their `poll()`
    // method and (2) have the `panic!` triggered in their `poll()` method (or in a directly
    // nested concrete future).
```

File: hydro_lang/src/sim/compiled.rs [hunk 2]
```diff
@@ -514,29 +523,104 @@ impl<T: Serialize + DeserializeOwned> SimReceiver<T, TotalOrder, ExactlyOnce> {
...
+    ) -> std::task::Poll<Self::Output> {
+        match ready!(self.as_mut().project().future.poll(cx)) {
+            Ok(()) => std::task::Poll::Ready(()),
+            Err(e) => panic!("{}", e),
+        }
+    }
+}
+
+pin_project_lite::pin_project! {
+    // A future that first awaits the first future, then the second, propagating caller info.
```
Comment (MingweiSamuel) [inline hydro_lang/src/sim/compiled.rs:608]:
```suggestion
    // A future that first awaits the first future, then the second, propagating caller info.
    //
    // See [`FutureTrackingCaller`] for context.
```
