### PR TITLE
feat(hydro_lang): add broadcast_closed for fixed-membership clusters

### LINKED ISSUE #2803: feat(hydro_lang): `broadcast_closed` for prototyping
In experimental settings, we often assume a static cluster membership, which allows us to write prototype programs we can easily test for consistency and other properties. In particular, regular `broadcast` has a `nondet!` to account for the fact that there can be "late joiners" in a broadcast stream who miss a non-deterministic prefix of the stream.

`broadcast_closed` provides the deterministic transport suitable for such prototypes:
- it pulls the initial destination Cluster membership from hydro deploy as a Bounded Stream on initialization
- broadcast is simply a join of Unbounded messages stream with Bounded and unchanging member stream 
- If new nodes enter the cluster, it generates a runtime `panic!`. 

The `panic!` is acceptable behavior, as we don't foresee a use case for `closed_broadcast` in production.

### PR DESCRIPTION
**Pull request by jhellerstein**
Adds `Stream::broadcast_closed`, a deterministic alternative to `broadcast` for clusters with fixed deploy-time membership.

Unlike `broadcast`, this does not require a `NonDet` guard — the membership set is obtained via `source_iter` over `ClusterIds`, producing a `Bounded` stream. The cross-product of data × members is fully deterministic.

Useful for prototyping and testing with fixed-size clusters.

Depends on #2778 (mixed-boundedness `cross_product`).

Closes #2803

### CODE REVIEW

File: hydro_lang/src/live_collections/boundedness.rs [hunk 1]
```diff
@@ -23,6 +23,13 @@ pub trait Boundedness:
...
         BoundKind::Unbounded
     };
+
+    /// Determines the output ordering of a join based on this (right/build) side's boundedness.
+    ///
+    /// When this side is [`Bounded`], the join accumulates this side first and then
+    /// streams the left side through, preserving the left side's ordering `InO`.
+    /// When this side is [`Unbounded`], a symmetric hash join is used and ordering is lost.
+    type PreserveOrderIfBounded<InO: crate::live_collections::stream::Ordering>: crate::live_collections::stream::Ordering;
 }
```
[the remark this answers is not in the document]
Comment (jhellerstein) [reply hydro_lang/src/live_collections/boundedness.rs:33]: ignore; flip-flopping AI

File: hydro_lang/src/live_collections/stream/networking.rs [hunk 2]
```diff
@@ -309,6 +310,85 @@ impl<'a, T, L, B: Boundedness, O: Ordering, R: Retries> Stream<T, Process<'a, L>
...
+    pub fn broadcast_closed<L2: 'a, N: NetworkFor<T>>(
+        self,
+        to: &Cluster<'a, L2>,
+        via: N,
+    ) -> Stream<T, Cluster<'a, L2>, Unbounded, <O as MinOrder<N::OrderingGuarantee>>::Min, R>
+    where
+        T: Clone + Serialize + DeserializeOwned,
+        O: MinOrder<N::OrderingGuarantee>,
+    {
+        let cluster_ids = ClusterIds {
```
Comment (shadaj) [inline hydro_lang/src/live_collections/stream/networking.rs:359]: So I realized while reviewing this PR, that actually `ClusterIds` is only available in environments that allow static clusters anyways (those being "legacy" Hydro Deploy and simulation tests). So we don't actually need to insert the panic guard, because deploying `broadcast_closed` will actually just fail compilation during staging if the deployment target is dynamic (i.e. ECS).

Simulator is a bit of an interesting one, because it can actually simulate dynamic member joins, but *automatically skips* simulating those when you use `ClusterIds`. So regular broadcast will correctly show dynamic member joins in simulation, but `broadcast_closed` won't. Probably worth documenting...

Comment (jhellerstein) [reply hydro_lang/src/live_collections/stream/networking.rs:359]: Seems harmless and maybe a healthy regression test to maintain the panic guard -- it is zero-compute overhead in the environments where this will compile, and not hard to read or maintain.

Can add a comment that the simulator will not exercise the dynamic clusters in this case.

Comment (jhellerstein) [reply hydro_lang/src/live_collections/stream/networking.rs:359]: After discussion, we agreed that:

1. It is safe for late joiners to receive NO data -- "eventually consistent" in a weak sense, and future-monotone in the Coordination Criterion sense.
2. Hence we will in fact remove the panic guard and document the late-joiners-get-nothing semantics.

File: hydro_lang/src/live_collections/stream/networking.rs [hunk 3]
```diff
@@ -309,6 +310,70 @@ impl<'a, T, L, B: Boundedness, O: Ordering, R: Retries> Stream<T, Process<'a, L>
...
+    /// [`ClusterIds`], producing a
+    /// `Bounded` stream. The cross-product of data × members is fully
+    /// deterministic.
+    ///
+    /// This is only available in deployment targets with static cluster
+    /// membership (legacy Hydro Deploy and simulation). On dynamic targets
+    /// (e.g. ECS), use [`Stream::broadcast`] instead.
+    ///
+    /// In simulation, dynamic member joins are automatically skipped
+    /// when `ClusterIds` is used, so late joiners will not receive data
```
Comment (shadaj) [inline hydro_lang/src/live_collections/stream/networking.rs]: Not quite accurate, replace with `is used, so the broadcast will send to all cluster members, including those that officially join the cluster in the future (according to the membership event stream)`.

**Review by shadaj — APPROVED** [review]
One comment, feel free to merge after.

**Comment by shadaj** [comment]
I think this should be a draft still because it is stacked on #2778?

File: hydro_lang/src/live_collections/stream/networking.rs (hunk 3 above)
Comment (jhellerstein) [reply hydro_lang/src/live_collections/stream/networking.rs]: fixed as suggested

**Comment by jhellerstein** [comment]
@copilot resolve the merge conflicts in this pull request

File: hydro_lang/src/live_collections/stream/networking.rs [hunk 4]
```diff
@@ -309,6 +310,77 @@ impl<'a, T, L, B: Boundedness, O: Ordering, R: Retries> Stream<T, Process<'a, L>
...
+    /// (e.g. ECS), use [`Stream::broadcast`] instead.
+    ///
+    /// **Late joiners receive no data.** Members that join the cluster after the
+    /// cross-product has been computed will not receive any elements. This is
+    /// safe: it is future-monotone and eventually consistent (a safe
+    /// under-approximation).
+    ///
+    /// In simulation, [`ClusterIds`] only reflects the initial cluster size set
+    /// at deploy time (via `with_cluster_size`). Members that join the cluster
+    /// dynamically during simulation are not included in `ClusterIds`, so they
```
Comment (shadaj) [inline hydro_lang/src/live_collections/stream/networking.rs]: This is wrong, `ClusterIds` represents the **maximum** set of cluster members that will be present at any time across the simulation.

File: hydro_lang/src/live_collections/stream/networking.rs [hunk 5]
```diff
@@ -309,6 +310,77 @@ impl<'a, T, L, B: Boundedness, O: Ordering, R: Retries> Stream<T, Process<'a, L>
...
+    /// The membership set is obtained from deploy metadata via
+    /// [`ClusterIds`], producing a
+    /// `Bounded` stream. The cross-product of data × members is fully
+    /// deterministic.
+    ///
+    /// This is only available in deployment targets with static cluster
+    /// membership (legacy Hydro Deploy and simulation). On dynamic targets
+    /// (e.g. ECS), use [`Stream::broadcast`] instead.
+    ///
+    /// **Late joiners receive no data.** Members that join the cluster after the
```
Comment (shadaj) [inline hydro_lang/src/live_collections/stream/networking.rs]: This comment isn't relevant, because there are no late joiners in static cluster membership targets.

**Review by shadaj — CHANGES_REQUESTED** [review]

File: hydro_lang/src/live_collections/stream/networking.rs (hunk 5 above)
Comment (jhellerstein) [reply hydro_lang/src/live_collections/stream/networking.rs]: Grrr thanks will fix.

**Review by shadaj — APPROVED** [review]
Awesome!
