### PR TITLE
fix(hydro_lang): correctly handle non-debug types in `__maybe_debug__`

### LINKED ISSUE #2596: Simulator does not correctly handle non-debuggable types
```
error[E0277]: `Test` doesn't implement `Debug`
  --> dylib-examples/examples/22B40BD4.rs:80:36
   |
80 |                 format_item_debug: hydro_lang::__maybe_debug__!(),
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Debug` is not implemented for `Test`
   |
note: required by a bound in `IsDebug::<T>::format_debug`
  --> dylib-examples/examples/22B40BD4.rs:80:36
   |
80 |                 format_item_debug: hydro_lang::__maybe_debug__!(),
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                                    |
   |                                    required by a bound in this associated function
   |                                    required by this bound in `IsDebug::<T>::format_debug`
   = note: this error originates in the macro `hydro_lang::__maybe_debug__` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by shadaj**
Fixes #2596

### CODE REVIEW

File: hydro_lang/src/sim/runtime.rs [hunk 1]
```diff
@@ -15,24 +15,46 @@ use crate::live_collections::stream::{NoOrder, Ordering, TotalOrder};
...
-    () => {{
-        trait NotDebug {
-            fn format_debug(&self) -> Option<String> {
-                None
-            }
+    ($type:ty) => {{
+        // Inherent-shadows-trait trick (same as `impls` crate), but for
+        // a function pointer. The const is stored as a raw `*const ()` to
+        // avoid mentioning the type in the const type (which would force
+        // bound resolution and break the trick). We transmute back at the end.
```
Comment (MingweiSamuel) [inline hydro_lang/src/sim/runtime.rs:26]: Do you have a link to where you figured out how to do this magic?

Comment (shadaj) [reply hydro_lang/src/sim/runtime.rs:26]: https://github.com/nvzqz/impls
